<a href="https://colab.research.google.com/github/kevinkamm/RatingML/blob/main/RatingNotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://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@github.com/kevinkamm/RatingML.git

Cloning into 'RatingML'...
remote: Enumerating objects: 279, done.
remote: Counting objects: 100% (279/279), done.
remote: Compressing objects: 100% (235/235), done.
remote: Total 279 (delta 44), reused 270 (delta 40), pack-reused 0
Receiving objects: 100% (279/279), 736.28 KiB | 9.56 MiB/s, done.
Resolving deltas: 100% (44/44), done.


In [3]:
ls

RatingML/  sample_data/


In [4]:
cd 'RatingML'

/content/RatingML


In [6]:
# from RatingTimeGAN import timeGAN as tg
# from RatingTimeGAN import loadRatingMatrices as lrm
# from RatingTimeGAN import brownianMotion as bm
from RatingTimeGAN import TimeGAN,BrownianMotion,getTimeIndex,RML

import numpy as np
import tensorflow as tf

from typing import List

import time as timer

#tf.config.set_visible_devices([], 'GPU')
print(tf.config.experimental.get_synchronous_execution())
print(tf.config.experimental.list_physical_devices())
print(tf.config.threading.get_inter_op_parallelism_threads())
print(tf.config.threading.get_intra_op_parallelism_threads())

'Data type for computations'
# use single precision for GeForce GPUs
dtype = np.float32

# seed for reproducibility
seed = 0
tf.random.set_seed(seed)

'Parameters for Brownian motion'
# time steps of Brownian motion, has to be such that mod(N-1,12)=0
N = 5 * 12 + 1
# trajectories of Brownian motion will be equal to batch_size for training
# M = batch_size = 1
# number of independent Brownian motions, takes the role of latent dimension
n = 1
# Brownian motion class with fixed datatype
BM = BrownianMotion(dtype=dtype, seed=seed)

'Load rating matrices'
# choose between 1,3,6,12 months
times = np.array([1, 3, 6, 12])
lenSeq = times.size
T = times[-1] / 12
timeIndices = getTimeIndex(T, N, times / 12)
# relative path to rating matrices:
filePaths: List[str] = ['Data/' + 'SP_' + str(x) + '_month_small' for x in times]
# exclude default row, don't change
# excludeDefaultRow = False
# permuteTimeSeries, don't change
# permuteTimeSeries = True
# load rating matrices
RML = RML(filePaths,
              dtype=dtype)
print('Load data')
ticRML = timer.time()
RML.loadData()
ctimeRML = timer.time() - ticRML
print(f'Elapsed time for loading data {ctimeRML} s.')

'Build GAN'
# training data
rm_train = RML.tfData()
print(f'Data shape: (Data,Time Seq,From Rating*To Rating)={rm_train.shape}')
# number of ratings
Krows = RML.Krows
Kcols = RML.Kcols
# batch size
batch_size = 128

# buffer size should be greater or equal number of data,
# is only important if data doesn't fit in RAM
buffer_size = rm_train.shape[0]

dataset = tf.data.Dataset.from_tensor_slices(rm_train)
dataset = dataset.shuffle(buffer_size, reshuffle_each_iteration=True).batch(batch_size)

epochs = 20
saveDir = 'RatingTimeGAN/modelParams'
tGAN = TimeGAN(lenSeq, Krows, Kcols, batch_size, dtype=dtype)
tGAN.trainTimeGAN(dataset, BM, T, N, timeIndices, epochs, loadDir=saveDir)
tGAN.save(saveDir)
samples = tGAN.sample(BM,T,N,timeIndices, 10)
print(samples.shape)
samples = np.reshape(samples, (samples.shape[0], samples.shape[1], Krows, Kcols))
print(samples.shape)
for wi in range(0, 3):
    print(f'Trajectory {wi}\n')
    for ti in range(0, samples.shape[1]):
        print(f'Time {timeIndices[ti]}')
        print(samples[wi, ti, :, :])
        print(np.sum(samples[wi, ti, :, :], axis=1))

True
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
0
0
Load data
Elapsed time for loading data 4.7782793045043945 s.
Data shape: (Data,Time Seq,From Rating*To Rating)=(629856, 4, 16)


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch512_epochs10/embeddedGenerator/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch512_epochs10/embeddedGenerator/assets
Synthetic data generation: 100%|██████████| 1/1 [00:00<00:00,  5.27it/s]


(512, 4, 16)
(512, 4, 4, 4)
Trajectory 0

Time 5
[[9.9082983e-01 7.9548061e-03 3.6994517e-03 9.4795227e-04]
 [2.9388368e-03 9.9160922e-01 4.4752955e-03 2.3459196e-03]
 [1.5863180e-03 1.2226790e-02 9.5766389e-01 2.1192521e-02]
 [1.4675856e-03 1.8945932e-03 1.9982755e-03 9.9853188e-01]]
[1.003432  1.0013692 0.9926696 1.0038923]
Time 15
[[0.98612446 0.01279271 0.00481164 0.00134301]
 [0.00381821 0.98920393 0.00612044 0.00362191]
 [0.00247529 0.01553631 0.9418616  0.03336293]
 [0.00219804 0.00309864 0.00289819 0.9975045 ]]
[1.0050719 1.0027645 0.9932361 1.0056994]
Time 30
[[0.97224796 0.02708372 0.00796962 0.00273842]
 [0.00648949 0.98266184 0.01125669 0.00773293]
 [0.00529972 0.02481115 0.9072491  0.06524295]
 [0.00478286 0.0070743  0.00560793 0.99402714]]
[1.0100398 1.008141  1.0026028 1.0114923]
Time 60
[[0.95051974 0.05059627 0.01224691 0.00502941]
 [0.01020086 0.97410107 0.01886913 0.01469365]
 [0.01011178 0.03683385 0.8644191  0.11249468]
 [0.00925705 0.01422063 0.00982857 0.98749936