<a href="https://colab.research.google.com/github/kevinkamm/RatingML/blob/main/RatingNotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!git clone https://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@github.com/kevinkamm/RatingML.git

Cloning into 'RatingML'...
remote: Enumerating objects: 282, done.
remote: Counting objects: 100% (282/282), done.
remote: Compressing objects: 100% (238/238), done.
remote: Total 282 (delta 46), reused 270 (delta 40), pack-reused 0
Receiving objects: 100% (282/282), 739.67 KiB | 1.08 MiB/s, done.
Resolving deltas: 100% (46/46), done.


In [4]:
ls

RatingML/  sample_data/


In [5]:
cd 'RatingML'

/content/RatingML


In [6]:
# from RatingTimeGAN import timeGAN as tg
# from RatingTimeGAN import loadRatingMatrices as lrm
# from RatingTimeGAN import brownianMotion as bm
from RatingTimeGAN import TimeGAN,BrownianMotion,getTimeIndex,RML

import numpy as np
import tensorflow as tf

from typing import List

import time as timer

#tf.config.set_visible_devices([], 'GPU')
print(tf.config.experimental.get_synchronous_execution())
print(tf.config.experimental.list_physical_devices())
print(tf.config.threading.get_inter_op_parallelism_threads())
print(tf.config.threading.get_intra_op_parallelism_threads())

'Data type for computations'
# use single precision for GeForce GPUs
dtype = np.float32

# seed for reproducibility
seed = 0
tf.random.set_seed(seed)

'Parameters for Brownian motion'
# time steps of Brownian motion, has to be such that mod(N-1,12)=0
N = 5 * 12 + 1
# trajectories of Brownian motion will be equal to batch_size for training
# M = batch_size = 1
# number of independent Brownian motions, takes the role of latent dimension
n = 1
# Brownian motion class with fixed datatype
BM = BrownianMotion(dtype=dtype, seed=seed)

'Load rating matrices'
# choose between 1,3,6,12 months
times = np.array([1, 3, 6, 12])
lenSeq = times.size
T = times[-1] / 12
timeIndices = getTimeIndex(T, N, times / 12)
# relative path to rating matrices:
filePaths: List[str] = ['Data/' + 'SP_' + str(x) + '_month_small' for x in times]
# exclude default row, don't change
# excludeDefaultRow = False
# permuteTimeSeries, don't change
# permuteTimeSeries = True
# load rating matrices
RML = RML(filePaths,
              dtype=dtype)
print('Load data')
ticRML = timer.time()
RML.loadData()
ctimeRML = timer.time() - ticRML
print(f'Elapsed time for loading data {ctimeRML} s.')

'Build GAN'
# training data
rm_train = RML.tfData()
print(f'Data shape: (Data,Time Seq,From Rating*To Rating)={rm_train.shape}')
# number of ratings
Krows = RML.Krows
Kcols = RML.Kcols
# batch size
batch_size = 128

# buffer size should be greater or equal number of data,
# is only important if data doesn't fit in RAM
buffer_size = rm_train.shape[0]

dataset = tf.data.Dataset.from_tensor_slices(rm_train)
dataset = dataset.shuffle(buffer_size, reshuffle_each_iteration=True).batch(batch_size)

epochs = 20
saveDir = 'RatingTimeGAN/modelParams'
tGAN = TimeGAN(lenSeq, Krows, Kcols, batch_size, dtype=dtype)
tGAN.trainTimeGAN(dataset, BM, T, N, timeIndices, epochs, loadDir=saveDir)
tGAN.save(saveDir)
samples = tGAN.sample(BM,T,N,timeIndices, 10)
print(samples.shape)
samples = np.reshape(samples, (samples.shape[0], samples.shape[1], Krows, Kcols))
print(samples.shape)
for wi in range(0, 3):
    print(f'Trajectory {wi}\n')
    for ti in range(0, samples.shape[1]):
        print(f'Time {timeIndices[ti]}')
        print(samples[wi, ti, :, :])
        print(np.sum(samples[wi, ti, :, :], axis=1))

True
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
0
0
Load data
Elapsed time for loading data 4.329283237457275 s.
Data shape: (Data,Time Seq,From Rating*To Rating)=(629856, 4, 16)

train autoencoder


Autoencoder network training:   0%|          | 0/20 [00:00<?, ?it/s]

Autoencoder network training: 100%|██████████| 20/20 [17:59<00:00, 53.96s/it]



train supervisor


Supervised network training: 100%|██████████| 20/20 [08:51<00:00, 26.59s/it]



train joint model


Joint network training:   0%|          | 0/20 [00:00<?, ?it/s]

Joint network training: 100%|██████████| 20/20 [2:06:55<00:00, 380.78s/it]

INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/generator/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/generator/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/autoencoder/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/autoencoder/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/recovery/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/recovery/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/embedder/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/embedder/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/supervisor/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/supervisor/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/discriminator/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/discriminator/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/discriminator_model/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/discriminator_model/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/embeddedGAN/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/embeddedGAN/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/embeddedGenerator/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/embeddedGenerator/assets
Synthetic data generation: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]

(128, 4, 16)
(128, 4, 4, 4)
Trajectory 0

Time 5
[[9.9416155e-01 5.8619808e-03 6.5708527e-06 3.0696540e-07]
 [1.0357334e-03 9.9659181e-01 2.4506161e-03 3.0548574e-05]
 [1.6494494e-05 4.0991427e-03 9.8660177e-01 9.0203471e-03]
 [2.3883791e-07 1.8911628e-07 1.4463104e-07 9.9999988e-01]]
[1.0000304  1.0001087  0.99973774 1.0000005 ]
Time 15
[[9.8517841e-01 1.4776895e-02 4.6074772e-05 2.8133986e-06]
 [2.4886490e-03 9.9105448e-01 6.1444659e-03 1.9421593e-04]
 [8.6986358e-05 1.1352147e-02 9.5527893e-01 3.1235797e-02]
 [1.2597037e-06 1.1153249e-06 9.7935151e-07 9.9999905e-01]]
[1.0000043 0.9998818 0.9979539 1.0000024]
Time 30
[[9.68727231e-01 3.09773330e-02 2.43527087e-04 2.06885070e-05]
 [4.98056319e-03 9.79852319e-01 1.34451315e-02 1.09576248e-03]
 [3.52438103e-04 2.49555372e-02 8.75554204e-01 9.53654423e-02]
 [5.59319051e-06 5.49347396e-06 5.36711923e-06 9.99994636e-01]]
[0.99996877 0.9993738  0.9962276  1.0000111 ]
Time 60
[[9.4864655e-01 5.0551459e-02 6.9590262e-04 7.2023475e-05]
 [8.568

In [ ]:
!zip -r /content/modelParams.zip /content/RatingML/RatingTimeGAN/modelParams/