<a href="https://colab.research.google.com/github/kevinkamm/RatingML/blob/main/RatingNotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://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@github.com/kevinkamm/RatingML.git
!git remote add origin https://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@github.com/kevinkamm/RatingML.git

Cloning into 'RatingML'...
remote: Enumerating objects: 352, done.
remote: Counting objects: 100% (352/352), done.
remote: Compressing objects: 100% (274/274), done.
remote: Total 352 (delta 87), reused 330 (delta 74), pack-reused 0
Receiving objects: 100% (352/352), 1000.05 KiB | 5.65 MiB/s, done.
Resolving deltas: 100% (87/87), done.
fatal: not a git repository (or any of the parent directories): .git


In [2]:
ls

RatingML/  sample_data/


In [3]:
cd 'RatingML'

/content/RatingML


In [6]:
import tensorflow
print(tensorflow.__version__)

2.8.0


In [4]:
# from RatingTimeGAN import timeGAN as tg
# from RatingTimeGAN import loadRatingMatrices as lrm
# from RatingTimeGAN import brownianMotion as bm
from RatingTimeGAN import TimeGAN,BrownianMotion,getTimeIndex,RML

import numpy as np
import tensorflow as tf

from typing import List

import time as timer

#tf.config.set_visible_devices([], 'GPU')
print(tf.config.experimental.get_synchronous_execution())
print(tf.config.experimental.list_physical_devices())
print(tf.config.threading.get_inter_op_parallelism_threads())
print(tf.config.threading.get_intra_op_parallelism_threads())

'Data type for computations'
# use single precision for GeForce GPUs
dtype = np.float32

# seed for reproducibility
seed = 0
tf.random.set_seed(seed)

'Parameters for Brownian motion'
# time steps of Brownian motion, has to be such that mod(N-1,12)=0
N = 5 * 12 + 1
# trajectories of Brownian motion will be equal to batch_size for training
# M = batch_size = 1
# number of independent Brownian motions, takes the role of latent dimension
n = 1
# Brownian motion class with fixed datatype
BM = BrownianMotion(dtype=dtype, seed=seed)

'Load rating matrices'
# choose between 1,3,6,12 months
times = np.array([1, 3, 6, 12])
lenSeq = times.size
T = times[-1] / 12
timeIndices = getTimeIndex(T, N, times / 12)
# relative path to rating matrices:
filePaths: List[str] = ['Data/' + 'SP_' + str(x) + '_month_small' for x in times]
# exclude default row, don't change
# excludeDefaultRow = False
# permuteTimeSeries, don't change
# permuteTimeSeries = True
# load rating matrices
RML = RML(filePaths,
              dtype=dtype)
print('Load data')
ticRML = timer.time()
RML.loadData()
ctimeRML = timer.time() - ticRML
print(f'Elapsed time for loading data {ctimeRML} s.')

'Build GAN'
# training data
rm_train = RML.tfData()
print(f'Data shape: (Data,Time Seq,From Rating*To Rating)={rm_train.shape}')
# number of ratings
Krows = RML.Krows
Kcols = RML.Kcols
# batch size
batch_size = 128

# buffer size should be greater or equal number of data,
# is only important if data doesn't fit in RAM
buffer_size = rm_train.shape[0]

dataset = tf.data.Dataset.from_tensor_slices(rm_train)
dataset = dataset.shuffle(buffer_size, reshuffle_each_iteration=True).batch(batch_size)

epochs = 20
saveDir = 'RatingTimeGAN/modelParams/Colab'
tGAN = TimeGAN(lenSeq, Krows, Kcols, batch_size, dtype=dtype)
tGAN.trainTimeGAN(dataset, BM, T, N, timeIndices, epochs, loadDir=saveDir)
tGAN.save(saveDir)
samples = tGAN.sample(BM,T,N,timeIndices, 10)
print(samples.shape)
samples = np.reshape(samples, (samples.shape[0], samples.shape[1], Krows, Kcols))
print(samples.shape)
for wi in range(0, 3):
    print(f'Trajectory {wi}\n')
    for ti in range(0, samples.shape[1]):
        print(f'Time {timeIndices[ti]}')
        print(samples[wi, ti, :, :])
        print(np.sum(samples[wi, ti, :, :], axis=1))

True
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
0
0
Load data
Elapsed time for loading data 4.414698123931885 s.
Data shape: (Data,Time Seq,From Rating*To Rating)=(629856, 4, 16)


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/embeddedGenerator/assets


INFO:tensorflow:Assets written to: /content/RatingML/RatingTimeGAN/modelParams/AE560_G854_lenSeq4_batch128_epochs20/embeddedGenerator/assets
Synthetic data generation: 100%|██████████| 1/1 [00:02<00:00,  2.76s/it]

(128, 4, 16)
(128, 4, 4, 4)
Trajectory 0

Time 5
[[9.9411738e-01 5.9059188e-03 6.6660773e-06 3.1171493e-07]
 [1.0437837e-03 9.9656713e-01 2.4679150e-03 3.0890329e-05]
 [1.6707698e-05 4.1348864e-03 9.8650151e-01 9.0830242e-03]
 [2.4185800e-07 1.9158472e-07 1.4667417e-07 9.9999988e-01]]
[1.0000303  1.0001097  0.99973613 1.0000005 ]
Time 15
[[9.9208844e-01 7.9272762e-03 1.2062586e-05 5.9406466e-07]
 [1.3849541e-03 9.9538344e-01 3.2645823e-03 5.1938499e-05]
 [2.7899934e-05 5.7679717e-03 9.8073155e-01 1.2906256e-02]
 [3.9312349e-07 3.2143507e-07 2.5752576e-07 9.9999976e-01]]
[1.0000284 1.000085  0.9994337 1.0000007]
Time 30
[[9.9102730e-01 8.9899525e-03 1.4217739e-05 6.4031502e-07]
 [1.5964616e-03 9.9495524e-01 3.5323563e-03 5.0853203e-05]
 [3.3026645e-05 6.8603107e-03 9.8006666e-01 1.2625074e-02]
 [4.2359156e-07 3.4515480e-07 2.8308523e-07 9.9999976e-01]]
[1.0000321 1.000135  0.9995851 1.0000008]
Time 60
[[9.7971332e-01 2.0247795e-02 6.0445844e-05 2.4577409e-06]
 [3.6798127e-03 9.8947841e-

In [ ]:
!zip -r /content/modelParams.zip /content/RatingML/RatingTimeGAN/modelParams/

In [ ]:
!git config --global user.email 'kevinkamm@t-online.de'
!git config --global user.name 'Kevin'
!git add -A
!git commit -m 'new model parameters'
!git pull
!git push 